title: Text-template
description: Single-Class string template engine for PHP5 supporting if/loops/filters
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman
source: /README.md

gems:
- jekyll-mentions